version: '3'

services:

  neo4j:
    build: ./neo4j
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true

  api:
    build: ./
    command: ["npm", "start"]
    ports:
      - 4000:4000
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      HOST: "0.0.0.0"
      PORT: 4000
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "letmein"
      JWT_SECRET: "not-so-secret"
      JWT_AUTH_KEYS: "[{\"id\":\"local\",\"apiKey\":\"PZsG+oEW3K3QOoB5z0f30InzjXdBqM9LMtJa7BTg1xo=\",\"scopes\":[\"*\"]}]"
      JWT_ISSUER: "https://api.trompamusic.eu"
      JWT_EXPIRES: "1d"
      DEBUG: ce-api-*
    volumes:
      - ./src:/app/src
    links:
      - neo4j
