name: Check licenses
on: [push]
jobs:
  check-licenses:
    name: Check if all used licenses are green
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn check-licenses
        name: Assert if all licenses are green
